name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest-xlarge
    steps:
     - name: Mount list
       run:  mount
     - name: Run df
       run: df -h
     - name: Print0
       run: uname -a
     - name: ls root
       run: ls -l /
     - name: pwd
       run: pwd
     # - name: find
     #   run: echo ~ && cd ~ && find .
